-- MySQL Script generated by MySQL Workbench
-- Mon Apr  8 04:20:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gebruiker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gebruiker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gebruiker` (
  `id` INT NOT NULL,
  `Voornaam` VARCHAR(45) NULL,
  `Achternaam` VARCHAR(45) NULL,
  `Tussenvoegsel` VARCHAR(45) NULL,
  `Geboortedatum` DATE NULL,
  `Mobielnummer` INT NULL,
  `Gebruikersnaam` VARCHAR(45) NULL,
  `Wachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pakket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pakket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pakket` (
  `id` INT NOT NULL,
  `Inpakdatum` DATE NULL,
  `Uitgavedatum` DATE NULL,
  `THT` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rollen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rollen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rollen` (
  `id` INT NOT NULL,
  `Rolnaam` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Leverancier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Leverancier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Leverancier` (
  `bedrijfsnummer` INT NOT NULL,
  `Rollen_id` INT NOT NULL,
  `bedrijfsnaam` VARCHAR(45) NULL,
  `contactpersoon` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefoonnummer` INT NULL,
  PRIMARY KEY (`bedrijfsnummer`, `Rollen_id`),
  INDEX `fk_Leverancier_Rollen1_idx` (`Rollen_id` ASC),
  CONSTRAINT `fk_Leverancier_Rollen1`
    FOREIGN KEY (`Rollen_id`)
    REFERENCES `mydb`.`Rollen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Levering`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Levering` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Levering` (
  `id` INT NOT NULL,
  `Leverancier_id` INT NOT NULL,
  `Datum` DATE NULL,
  `Eerstvolgende` DATE NULL,
  `Meestrecente` DATE NULL,
  PRIMARY KEY (`id`, `Leverancier_id`),
  INDEX `fk_Levering_Leverancier1_idx` (`Leverancier_id` ASC),
  CONSTRAINT `fk_Levering_Leverancier1`
    FOREIGN KEY (`Leverancier_id`)
    REFERENCES `mydb`.`Leverancier` (`bedrijfsnummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Adres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Adres` (
  `id` INT NOT NULL,
  `Postcode` VARCHAR(6) NULL,
  `Huisnummer` INT NULL,
  `Straatnaam` VARCHAR(45) NULL,
  `Land` VARCHAR(45) NULL,
  `Gebruiker_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Gebruiker_id`),
  INDEX `fk_Adres_Gebruiker1_idx` (`Gebruiker_id` ASC),
  CONSTRAINT `fk_Adres_Gebruiker1`
    FOREIGN KEY (`Gebruiker_id`)
    REFERENCES `mydb`.`Gebruiker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Samenstelling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Samenstelling` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Samenstelling` (
  `id` INT NOT NULL,
  `Volwassenen` INT NULL,
  `Kinderen` INT NULL,
  `Babys` INT NULL,
  `Gebruiker_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Gebruiker_id`),
  INDEX `fk_Samenstelling_Gebruiker1_idx` (`Gebruiker_id` ASC),
  CONSTRAINT `fk_Samenstelling_Gebruiker1`
    FOREIGN KEY (`Gebruiker_id`)
    REFERENCES `mydb`.`Gebruiker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voorkeuren`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Voorkeuren` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Voorkeuren` (
  `id` INT NOT NULL,
  `Voorkeurnaam` VARCHAR(45) NULL,
  `Gebruiker_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Gebruiker_id`),
  INDEX `fk_Voorkeuren_Gebruiker1_idx` (`Gebruiker_id` ASC),
  CONSTRAINT `fk_Voorkeuren_Gebruiker1`
    FOREIGN KEY (`Gebruiker_id`)
    REFERENCES `mydb`.`Gebruiker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Allergieen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Allergieen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Allergieen` (
  `id` INT NOT NULL,
  `Allergienaam` VARCHAR(45) NULL,
  `Gebruiker_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Gebruiker_id`),
  INDEX `fk_Allergieen_Gebruiker1_idx` (`Gebruiker_id` ASC),
  CONSTRAINT `fk_Allergieen_Gebruiker1`
    FOREIGN KEY (`Gebruiker_id`)
    REFERENCES `mydb`.`Gebruiker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inkomsten`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inkomsten` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inkomsten` (
  `id` INT NOT NULL,
  `Loon` INT NULL,
  `Uitkering` INT NULL,
  `Kindgebonden` INT NULL,
  `Gebruiker_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Gebruiker_id`),
  INDEX `fk_Inkomsten_Gebruiker1_idx` (`Gebruiker_id` ASC),
  CONSTRAINT `fk_Inkomsten_Gebruiker1`
    FOREIGN KEY (`Gebruiker_id`)
    REFERENCES `mydb`.`Gebruiker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uitgaven`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Uitgaven` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Uitgaven` (
  `id` INT NOT NULL,
  `Terugkerend` INT NULL,
  `Boodschappen` INT NULL,
  `Specialiteiten` INT NULL,
  `Gebruiker_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Gebruiker_id`),
  INDEX `fk_Uitgaven_Gebruiker1_idx` (`Gebruiker_id` ASC),
  CONSTRAINT `fk_Uitgaven_Gebruiker1`
    FOREIGN KEY (`Gebruiker_id`)
    REFERENCES `mydb`.`Gebruiker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL,
  `EAN` INT NOT NULL,
  `Naam` VARCHAR(45) NULL,
  `Aantal` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorieen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorieen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorieen` (
  `id` INT NOT NULL,
  `Categorieennaam` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorieen_has_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorieen_has_Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorieen_has_Product` (
  `Categorieen_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`Categorieen_id`, `Product_id`),
  INDEX `fk_Categorieen_has_Product_Product1_idx` (`Product_id` ASC),
  INDEX `fk_Categorieen_has_Product_Categorieen_idx` (`Categorieen_id` ASC),
  CONSTRAINT `fk_Categorieen_has_Product_Categorieen`
    FOREIGN KEY (`Categorieen_id`)
    REFERENCES `mydb`.`Categorieen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categorieen_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pakket_has_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pakket_has_Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pakket_has_Product` (
  `Pakket_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`Pakket_id`, `Product_id`),
  INDEX `fk_Pakket_has_Product_Product1_idx` (`Product_id` ASC),
  INDEX `fk_Pakket_has_Product_Pakket1_idx` (`Pakket_id` ASC),
  CONSTRAINT `fk_Pakket_has_Product_Pakket1`
    FOREIGN KEY (`Pakket_id`)
    REFERENCES `mydb`.`Pakket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pakket_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rollen_gebruiker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rollen_gebruiker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rollen_gebruiker` (
  `Rollen_id` INT NOT NULL,
  `Gebruiker_id` INT NOT NULL,
  PRIMARY KEY (`Rollen_id`, `Gebruiker_id`),
  INDEX `fk_Rollen_has_Gebruiker_Gebruiker1_idx` (`Gebruiker_id` ASC),
  INDEX `fk_Rollen_has_Gebruiker_Rollen1_idx` (`Rollen_id` ASC),
  CONSTRAINT `fk_Rollen_has_Gebruiker_Rollen1`
    FOREIGN KEY (`Rollen_id`)
    REFERENCES `mydb`.`Rollen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rollen_has_Gebruiker_Gebruiker1`
    FOREIGN KEY (`Gebruiker_id`)
    REFERENCES `mydb`.`Gebruiker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Levering`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product_has_Levering` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Levering` (
  `Product_id` INT NOT NULL,
  `Levering_id` INT NOT NULL,
  PRIMARY KEY (`Product_id`, `Levering_id`),
  INDEX `fk_Product_has_Levering_Levering1_idx` (`Levering_id` ASC),
  INDEX `fk_Product_has_Levering_Product1_idx` (`Product_id` ASC),
  CONSTRAINT `fk_Product_has_Levering_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Levering_Levering1`
    FOREIGN KEY (`Levering_id`)
    REFERENCES `mydb`.`Levering` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
